### ISSUE TITLE
Sublime Text 3 support

### ISSUE THREAD

**Issue by slokhorst** [harrism/sublimetext-cuda-cpp#6]
The description of this repository says "CUDA C++ package for Sublime Text 2" while the readme says "CUDA C++ package for Sublime Text 2 & 3".

This is not a big deal, but since the description is also shown in Package Control in Sublime, it suggests that this package does not work in Sublime 3.

Could you update the description of the repository?

**Comment by harrism** [comment]
Fixed. Thanks!
